title: Личный сайт Glebun08'а
url: "https://github.com/Gleb-Lisovskiy"
baseurl: ""
markdown: commonmark
#ins_logo: "./glebun08.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Владелец темы сайта Ankit Sultana."
footer_en_text: "The original owner of the theme is Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Обо мне"
   name_en: "About me "
   link: "index"
   link_en: "index_en"
 - name: "Контакт и другое"
   name_en: "Contact and other"
   link: "other"
   link_en: "other_en"
 - name: "Памятник"
   name_en: "Monument"
   link: "monument"
   link_en: "monument_en"
   

