title: Личный сайт Glebun08'а
url: "https://github.com/Gleb-Lisovskiy"
baseurl: ""
markdown: commonmark
#ins_logo: "./glebun08.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Владелец темы сайта Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Обо мне"
   link: "index"
 - name: "Контакт и другое"
   link: "other"
 - name: "Памятник"
   link: "monument"
   
 nav_en:
 - name: "About me
   link: "index_en"
 - name: "Contact and other"
   link: "other_en"
 - name: "Monument"
   link: "monument_en"
