title: Личный сайт Glebun08'а
url: "https://ankitsultana.com"
baseurl: ""
markdown: kramdown
#ins_logo: "./glebun08.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Владелец темы сайта Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Обо мне"
   link: "index"
 - name: "Контакт и другое"
   link: "other"
